version: "3"

services:

  pgdb:
    image: postgres:16
    ports:
      - "5438:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    command: python -m uvicorn architecton.app:app --host 0.0.0.0 --port 8000 --workers 1 --forwarded-allow-ips '*'
    environment:
      - DB_HOST=pgdb
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - NFTSCAN_APIKEY=${NFTSCAN_APIKEY}
      - SUB_CHECKER_BOT_HOST=http://sub_checker_bot:8001
      - TON_LSCLIENT=${TON_LSCLIENT}
      - TON_TESTNET=${TON_TESTNET}
      - TON_MANAGER_MNEMONIC=${TON_MANAGER_MNEMONIC}
    depends_on:
      - pgdb
